apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: ollama
spec:
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 80Gi
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: ollama
spec:
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
