apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-async-external-secrets
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store-ollama
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: externalsecrets-ollama-async
          serviceAccountRef:
            name: ollama-async-external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ollama-async-subscription-service-kafka
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-store-ollama
  target:
    name: ollama-async-subscription-service
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: KAFKA_SASL_USERNAME
      remoteRef:
        key: kafka-scram-user-ollama-async
        property: value
    - secretKey: KAFKA_SASL_PASSWORD
      remoteRef:
        key: kafka-scram-user-ollama-async-password
        property: value
