name: Validate Gravitee Health Checks

on:
  pull_request:
  push:
    branches:
      - prod
      - main
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install pyyaml
      - name: Validate Gravitee health checks
        run: python scripts/validate_gravitee_healthchecks.py manifests
